global:
  scrape_interval: 30s

#scrape minecraft server
scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['minecraft:9940']
        labels:
          server_name: 'minecraft-docker'